name: pytorch_a100_clone_Aug16
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - argon2-cffi=20.1.0=py38h7b6447c_1
  - async_generator=1.10=py_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.3=py38he30daa8_0
  - cudatoolkit=11.0.3=h15472ef_8
  - cycler=0.10.0=py_2
  - dbus=1.13.18=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - easydict=1.9=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.10=h9c3ff4c_0
  - fontconfig=2.13.1=hba837de_1004
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.68.0=h9c3ff4c_1
  - glib-tools=2.68.0=h9c3ff4c_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=hf484d3e_1000
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_1
  - jedi=0.18.0=py38h578d9bd_2
  - jinja2=2.11.2=py_0
  - joblib=0.17.0=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py38_0
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.3.1=py38h1fd1430_1
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglib=2.68.0=h3e27bee_1
  - libiconv=1.16=h516909a_0
  - libpng=1.6.37=h21135ba_2
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.41.0=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.10=hb55368b_3
  - llvm-openmp=11.1.0=h4bd325d_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.3.4=py38h578d9bd_0
  - matplotlib-base=3.3.4=py38h0efea84_0
  - mistune=0.8.4=py38h7b6447c_1000
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py38h1e0a361_2
  - mkl_fft=1.3.0=py38h5c078b8_1
  - mkl_random=1.2.0=py38hc5bc63f_1
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py38_0
  - nbformat=5.0.8=py_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.4.1=py_0
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.1.4=py38_0
  - numpy=1.19.2=py38h54aff64_0
  - numpy-base=1.19.2=py38hfa32c7d_0
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.4=py_0
  - pandas=1.1.3=py38he6710b0_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.2=py38_1
  - parso=0.8.0=py_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=8.1.2=py38he98fc37_0
  - pip=21.0.1=pyhd8ed1ab_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.6.0=py38_0
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - python=3.8.8=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytorch=1.7.1=py3.8_cuda11.0.221_cudnn8.0.5_0
  - pytz=2020.1=py_0
  - pyzmq=19.0.2=py38he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=he28a2e2_2
  - scikit-learn=0.24.2=py38hdc147b9_0
  - scipy=1.6.1=py38h91f5cce_0
  - seaborn=0.11.0=py_0
  - send2trash=1.5.0=py38_0
  - setuptools=49.6.0=py38h578d9bd_3
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h74cdb3f_0
  - terminado=0.9.1=py38_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h21135ba_1
  - torchaudio=0.7.2=py38
  - torchvision=0.8.2=py38_cu110
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.59.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py38_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.9=ha95c52a_0
prefix: /cluster/tufts/hugheslab/miniconda2/envs/pytorch_a100_clone_Aug16

